# Generated by Django 4.1.3 on 2022-11-05 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(verbose_name='Chat ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full name')),
                ('username', models.CharField(max_length=200, verbose_name='Username')),
                ('language_code', models.CharField(max_length=200, verbose_name='Full name')),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2022, 11, 5, 7, 24, 1, 924492), verbose_name='Date')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(verbose_name='Message ID')),
                ('chat_id', models.IntegerField(verbose_name='Chat ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full name')),
                ('username', models.CharField(max_length=200, verbose_name='Username')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 11, 5, 7, 24, 1, 924927), verbose_name='Date')),
                ('text', models.CharField(max_length=1500, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
    ]
