# Generated by Django 4.1.3 on 2022-11-05 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotuser',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 8, 38, 16, 224716), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='messagehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 8, 38, 16, 225582), verbose_name='Date'),
        ),
    ]
