# Generated by Django 4.1.3 on 2022-11-05 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0002_alter_chatbotuser_reg_date_alter_messagehistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotuser',
            name='language_code',
            field=models.CharField(max_length=200, verbose_name='language code'),
        ),
        migrations.AlterField(
            model_name='chatbotuser',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 8, 56, 53, 141288), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='messagehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 8, 56, 53, 141693), verbose_name='Date'),
        ),
    ]
