# Generated by Django 4.1.3 on 2022-11-21 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AlterField(
            model_name='chatbotuser',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 19, 8, 43, 355821), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='messagehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 19, 8, 43, 356821), verbose_name='Date'),
        ),
    ]
