# Generated by Django 4.1.2 on 2022-10-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full name')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('adress', models.CharField(max_length=200, verbose_name='Adress')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Phone')),
                ('current_balance', models.FloatField(verbose_name='Balance')),
                ('last_payment', models.DateTimeField(verbose_name='Last_payment')),
                ('reg_date', models.DateTimeField(verbose_name='Reg_date')),
                ('lastcall_date', models.DateTimeField(verbose_name='Lastcall date')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
